"""membuat tabel

Revision ID: 17e15a4e739c
Revises: 9ca2091ec2c2
Create Date: 2021-08-03 12:33:41.606507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17e15a4e739c'
down_revision = '9ca2091ec2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matakuliah', sa.Column('dosen_pengampu', sa.BigInteger(), nullable=True))
    op.drop_constraint('matakuliah_ibfk_1', 'matakuliah', type_='foreignkey')
    op.create_foreign_key(None, 'matakuliah', 'dosen', ['dosen_pengampu'], ['id'], ondelete='CASCADE')
    op.drop_column('matakuliah', 'dosen_satu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matakuliah', sa.Column('dosen_satu', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'matakuliah', type_='foreignkey')
    op.create_foreign_key('matakuliah_ibfk_1', 'matakuliah', 'dosen', ['dosen_satu'], ['id'], ondelete='CASCADE')
    op.drop_column('matakuliah', 'dosen_pengampu')
    # ### end Alembic commands ###
