"""buat tabel gambar

Revision ID: 574e2f8f6543
Revises: 79ed102d28c3
Create Date: 2021-07-23 15:53:10.790417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574e2f8f6543'
down_revision = '79ed102d28c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gambar',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('judul', sa.String(length=50), nullable=False),
    sa.Column('pathname', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gambar')
    # ### end Alembic commands ###
