"""wkwkwk

Revision ID: 91ecc5d87b78
Revises: e422ef33bfac
Create Date: 2021-08-04 18:02:39.318939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ecc5d87b78'
down_revision = 'e422ef33bfac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matakuliah',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kode_kuliah', sa.String(length=30), nullable=False),
    sa.Column('nama_mata_kuliah', sa.String(length=60), nullable=False),
    sa.Column('jumlah_sks', sa.BigInteger(), nullable=False),
    sa.Column('dosen_pengampu', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matakuliah')
    # ### end Alembic commands ###
