"""membuat tabel

Revision ID: 9f71752e5b6e
Revises: 54e56d56cfe3
Create Date: 2021-08-03 13:26:55.546900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f71752e5b6e'
down_revision = '54e56d56cfe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matakuliah', sa.Column('dosen_pengampus', sa.String(length=60), nullable=False))
    op.drop_column('matakuliah', 'dosen_pengampu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matakuliah', sa.Column('dosen_pengampu', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.drop_column('matakuliah', 'dosen_pengampus')
    # ### end Alembic commands ###
