"""wkwkwk

Revision ID: e422ef33bfac
Revises: 77fae5f6fc81
Create Date: 2021-08-04 18:01:54.140939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e422ef33bfac'
down_revision = '77fae5f6fc81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matakuliah', sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matakuliah', 'id')
    # ### end Alembic commands ###
